### ISSUE TITLE
crash when loading sample in complex simpler or quadsimpler

### ISSUE THREAD

**Issue by josbouten** [patman023/nysthimanual#9] opened 2019-04-20 14:40 UTC
Hi, the complex simpler continually crash when I'm trying to load a sample. Furthermore if I try the quad simpler as an alternative, it will not allow me to load a sample at all. Can you maybe remedy this?

I'm developing a plugin at the moment and I'm running Rack 0.6.2c from a terminal using ```make run```. The modules are shown but as soon as I try to load a wav-file Rack crashes with this output: ```: make: *** [run] Segmentation fault: 11 ```

**Comment by patman023** [comment] 2019-05-17 23:52
gah! never realized this was in here! sorry! 

I see you put this on the main nysthi page, closing as is not a bug in the documentation ;-)

**Closed by patman023** 2019-05-17 23:52 UTC
